ali/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from account.views import Login, Register, activate

urlpatterns = [
    path('', include('blog.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            activate, name='activate'),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('comment/', include('comment.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import ArticleList, Articledetail, categoryList, authorList, ArticlePreview, SearchList

app_name = "blog"
urlpatterns = [
    path('', ArticleList.as_view(), name="home"),
    path('page/<int:page>', ArticleList.as_view(), name="home"),
    path('article/<slug:slug>', Articledetail.as_view(), name="more"),
    path('category/<slug:slug>', categoryList.as_view(), name="category"),
    path('category/<slug:slug>/page/<int:page>', categoryList.as_view(), name="category"),
    path('author/<slug:username>', authorList.as_view(), name="author"),
    path('author/<slug:username>/page/<int:page>', authorList.as_view(), name="author"),
    path('preview/<int:pk>', ArticlePreview.as_view(), name="preview"),
    path('search/page/<int:page>', SearchList.as_view(), name="search"),
    path('search/', SearchList.as_view(), name="search"),
]

blog/models.py
from django.db import models
from account.models import User
from django.utils import timezone
from django.urls import reverse
from django.utils.html import format_html
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment
from extensions.util import jalali_converter


class articlemanager(models.Manager):
    def published(self):
        return self.filter(status='p')


class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)


class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL,
                               related_name='children', verbose_name="زیردسته")
    title = models.CharField(max_length=200000, verbose_name="عنوان دسته بندی")
    slug = models.SlugField(max_length=1000, unique=True, verbose_name="آدرس دسته بندی")
    status = models.BooleanField(default=True, verbose_name="نمایش بدم یا نه؟")
    position = models.IntegerField(verbose_name="پوزیشن")

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ['parent__id', 'position']

    def __str__(self):
        return self.title

    objects = CategoryManager()


class IpAddress(models.Model):
    ipaddress = models.GenericIPAddressField(verbose_name="آدرس ای پی")


class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش نویس'),
        ('p', 'منتشر شده'),
        ('i', 'درحال بررسی'),
        ('b', 'برگشت داده شده'),
    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='articles',
                               verbose_name="نویسنده")
    title = models.CharField(max_length=200000, verbose_name="عنوان مقاله")
    slug = models.SlugField(max_length=1000, unique=True, verbose_name="آدرس مقاله")
    category = models.ManyToManyField(Category, verbose_name="دسته بندی", related_name="articles")
    description = models.TextField(verbose_name="توضیحات")
    Image = models.ImageField(upload_to="image", verbose_name="عکس")
    publish = models.DateTimeField(default=timezone.now(), verbose_name="زمان انتشار")
    created = models.DateTimeField(auto_now_add=True, verbose_name="ساخته شده")
    update = models.DateTimeField(auto_now_add=True, verbose_name="بروزرسانی")
    is_special = models.BooleanField(default=False, verbose_name="مقاله ویژه")
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name="وضعیت")
    comments = GenericRelation(Comment)
    hits = models.ManyToManyField(IpAddress, through="ArticleHit", blank=True, related_name="hits",
                                  verbose_name="بازدید ها")

    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"
        ordering = ['-publish']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("account:home")

    def jpublish(self):
        return jalali_converter(self.publish)

    jpublish.short_description = "زمان انتشار "

    # def category_publish(self):
    #     return self.category.filter(status=True)
    def Image_tag(self):
        return format_html("<img style='border-radius: 5px;' width= 80  height= 75 src='{}'>".format(self.Image.url))

    Image_tag.short_description = "تصاویر"

    def category_to_str(self):
        return " ، ".join([category.title for category in self.category.active()])

    category_to_str.short_description = "دسته بندی"

    objects = articlemanager()

class ArticleHit(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IpAddress, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, verbose_name="ساخته شده")

blog/views.py
from account.models import User
from django.shortcuts import get_object_or_404
from .models import Article, Category
from account.mixins import AccessMixin
from django.views.generic import ListView, DetailView
from django.db.models import Q
# def home(request, page=1):
#     articles_list = Article.objects.published()
#     pagintor = Paginator(articles_list, 3)
#     articles = pagintor.get_page(page)
#     context = {
#         "articles": articles,
#     }
#     return render(request, "blog/index.html", context)
class ArticleList(ListView):
    template_name = "blog/index.html"
    queryset = Article.objects.published()
    paginate_by = 3
    context_object_name = "articles"


# def more(request, slug):
#     context = {
#         "article": get_object_or_404(Article.objects.published(), slug=slug),
#     }
#     return render(request, "blog/article_detail.html", context)
class Articledetail(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        article = get_object_or_404(Article.objects.published(), slug=slug)
        ipaddress = self.request.user.ipaddress
        if ipaddress not in article.hits.all():
            article.hits.add(ipaddress)
        return article


# def category(request, slug, page=1):
#     category = get_object_or_404(Category, slug=slug, status="True")
#     articles_list=category.articles.published()
#     pagintor = Paginator(articles_list, 3)
#     articles = pagintor.get_page(page)
#     context = {
#         "category": category,
#         "articles": articles,
#     }
#     return render(request, "blog/category.html", context)

class categoryList(ListView):
    paginate_by = 3
    template_name = "blog/category.html"

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context


class authorList(ListView):
    paginate_by = 3
    template_name = "blog/author_list.html"

    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(User, username=username)
        return author.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context


class ArticlePreview(AccessMixin, DetailView):
    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article, pk=pk)


class SearchList(ListView):
    paginate_by = 3
    template_name = "blog/search_list.html"

    def get_queryset(self):
        search = self.request.GET.get('q')
        return Article.objects.filter(Q(description__icontains=search) | Q(title__icontains=search))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.request.GET.get('q')
        return context

templates/blog/about.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="index.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="article_detail.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/about-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
            <span class="subheading">This is what I do.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

</body>

</html>

templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% load comment_tags %}
{% load ratings %}
{% load static %}
{% load base_tags %}
{% load humanize %}
{% block title %} | {{ article.title }} {% endblock %}
{% block main %}
    <header class="masthead" style="background-image: url('{{ article.Image.url }}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading" style="font-size: 20px">
                        <h1>{{ article.title }}</h1>
                        {% if article.is_special %}
                            <span class="badge badge-danger"> ویژه</span>
                        {% endif %}
                        <time class="asirefontshod">{{ article.publish | naturaltime }}</time>
                        <div>
                            {% ratings article %}
                        </div>
                        <div>
                            بازدید ها:{{ object.hits.count }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto text-justify">
                    <aside>
                        {% popular_articles %}
                        {% hot_articles %}
                    </aside>
                    {% if object.is_special %}
                        {% if user.is_authenticated and user.is_special_user or user == object.author or user.is_superuser %}
                            {{ article.description|safe }}
                        {% else %}
                            {{ article.description|striptags|truncatewords:30 }}
                            <p class="alert alert-warning"> این مقاله ویژه است</p>
                            <a class="alert-link" href="#">خرید اشتراک</a>
                        {% endif %}
                    {% else %}
                        {{ article.description|safe }}
                    {% endif %}
                    {% render_comments object request %}
                    {% include_static_jquery %}
                    {% include_bootstrap %}
                </div>
            </div>
        </div>
    </article>
{% endblock %}

templates/blog/author_list.html
{% extends 'blog/category.html' %}

{% block header %}
    <h3 class="alert alert-primary asirefontshod" style="text-align: center"> نویسنده
        :{{ author.get_full_name }}</h3>
{% endblock %}
{% block previous_page_url %}
    {% url 'blog:author' author.username  page_obj.previous_page_number %}
{% endblock %}
{% block next_page_url %}
    {% url 'blog:author' author.username  page_obj.next_page_number %}
{% endblock %}


templates/blog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>وبلاگ{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'blog/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">


    <!-- Custom styles for this template -->
    <link href="{% static 'blog/css/clean-blog.min.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand asirefontshod " href="{% url 'blog:home' %}">{% title %}</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        {% category_navbar %}
    </div>
</nav>

<!-- Page Header -->


<!-- Main Content -->
{% block main %}

{% endblock %}
<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'blog/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Custom scripts for this template -->
<script src="{% static 'blog/js/clean-blog.min.js' %}"></script>

</body>

</html>

templates/blog/basenew.html
{% extends 'blog/category.html' %}

{% block header %}

{% endblock %}
{% block previous_page_url %}
    {% url 'blog:home'   page_obj.previous_page_number %}
{% endblock %}
{% block next_page_url %}
    {% url 'blog:home'  page_obj.next_page_number %}
{% endblock %}

templates/blog/category.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %}
    <header class="masthead" style="background-image: url('{% static "blog/img/home-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>وبلاگ</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                {% block header %}

                {% endblock %}
                {% for article in object_list %}
                    <div class="post-preview asirefontshod">
                        <a href="{% url 'blog:more' article.slug %}">
                            <h2 class="post-title asirefontshod">
                                {{ article.title }}
                            </h2>
                            <h3 class="post-subtitle asirefontshod">
                                {{ article.description|truncatewords:30 }}
                            </h3>
                        </a>
                        <p class="post-meta">نوشته شده توسط
                            <a href="{% url 'blog:author' article.author %}">{{ article.author.get_full_name }}</a>
                            {{ article.jpublish }}</p>

                        <div>
                            {% for cat in article.category.active %}
                                <a href="{% url 'blog:category' cat.slug %}">#{{ cat.title }} </a>
                            {% endfor %}
                        </div>
                        <div>
                            بازدید ها:{{ article.hits.count }}
                        </div>
                    </div>
                    <hr>
                {% empty %}
                    <p>متاسفانه محتوی برای نمایش وجود ندارد</p>
                {% endfor %}

                <!-- Pager -->
                {% if is_paginated %}
                    <div class="clearfix">

                        {% if page_obj.has_previous %}
                            <a class="btn btn-primary float-left asirefontshod ml-3"
                               href="{% block previous_page_url %}{% endblock %}">پست های جدید &rarr;</a>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <a class="btn btn-primary float-left asirefontshod ml-3"
                               href="{% block next_page_url %}{% endblock %}">پست های قدیمی &Larr;</a>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

templates/blog/ghatishod.html
{% extends 'blog/category.html' %}

{% block header %}
    <h3 class="alert alert-primary asirefontshod" style="text-align: center"> دسته بندی
        :{{ category.title }}</h3>
{% endblock %}
{%  block previous_page_url %}
    {% url 'blog:category' category.slug  page_obj.previous_page_number %}
{% endblock %}
{%  block next_page_url %}
    {% url 'blog:category' category.slug  page_obj.next_page_number %}
{% endblock %}


templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}
{% load ratings %}
{% load base_tags %}
{% load humanize %}
{% block main %}
    <header class="masthead" style="background-image: url('{% static "blog/img/home-bg.jpg" %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>وبلاگ</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">

                {% block header %} {% endblock %}
                <aside>
                    {% popular_articles %}
                    {% hot_articles %}
                </aside>
                {% for article in object_list %}
                    <div class="post-preview asirefontshod">
                        <a href="{% url 'blog:more' article.slug %}">
                            <h2 class="post-title asirefontshod">
                                {{ article.title }}
                                {% if article.is_special %}
                                    <span class="badge badge-danger"> ویژه</span>
                                {% endif %}
                            </h2>
                            <div>
                                {% ratings article %}
                            </div>
                            <h3 class="post-subtitle asirefontshod">
                                {{ article.description|striptags|truncatewords:30 }}
                            </h3>
                        </a>
                        <p class="post-meta">نوشته شده توسط
                            <a href="{% url 'blog:author' article.author %}">{{ article.author.get_full_name }}</a>
                            {{ article.publish | naturaltime }}</p>

                        <div>
                            {% for cat in article.category_publish.all %}
                                <a href="{% url 'blog:category' cat.slug %}">#{{ cat.title }} </a>
                            {% endfor %}
                        </div>
                    </div>
                    <hr>
                {% endfor %}

                <!-- Pager -->
                {% if is_paginated %}
                    <div class="clearfix">

                        {% if page_obj.has_previous %}
                            <a class="btn btn-primary float-left asirefontshod ml-3"
                               href="{% url 'blog:home' page_obj.previous_page_number %}">پست های جدید &rarr;</a>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <a class="btn btn-primary float-left asirefontshod ml-3"
                               href="{% url 'blog:home' page_obj.next_page_number %}">پست های قدیمی &Larr;</a>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

templates/blog/search_list.html
{% extends 'blog/category.html' %}

{% block header %}
    <h3 class="alert alert-primary asirefontshod" style="text-align: center"> جستجو
        :{{ Search }}</h3>
{% endblock %}
{% block previous_page_url %}
    {% url 'blog:search'   page_obj.previous_page_number %}?q={{ Search }}
{% endblock %}
{% block next_page_url %}
    {% url 'blog:search'  page_obj.next_page_number %}?q={{ Search }}
{% endblock %}
